mod boundary;
mod collision;
pub mod debug;
mod handle_death;
mod movement;
mod player;
mod projectile;
mod setup;

pub use boundary::boundary_position_system;
pub use collision::collision;
pub use handle_death::add_score;
pub use handle_death::handle_death;
pub use movement::follow;
pub use movement::tracking;
pub use movement::update_movement;
pub use movement::update_tracking;
pub use player::player_input;
pub use projectile::constant_weapon_fire;
pub use projectile::despawn_projectile;
pub use projectile::weapon_fire_rate;
pub use projectile::weapon_fired;
pub use setup::setup;
pub use setup::MainCamera;
